### ISSUE TITLE
kaem.run: line 108: ./M2: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by practicalswift** [oriansj/mescc-tools-seed#1]
Thanks for all your excellent work!

I ran into the following when trying the mescc-tools-seed v1.0 release under Ubuntu 18.04.2 LTS:

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
$ uname -i
x86_64
$ wget https://github.com/oriansj/mescc-tools-seed/archive/Release_1.0.tar.gz
$ sha256sum Release_1.0.tar.gz
04bae061e1531172712ffed2493ce770545e020680335716a59a34efbbba4505  Release_1.0.tar.gz
$ tar xzf Release_1.0.tar.gz
$ cd mescc-tools-seed-Release_1.0
$ bash kaem.run
kaem.run: line 96:  8618 Segmentation fault      ./cc_x86 hold M2.M1
kaem.run: line 108: ./M2: cannot execute binary file: Exec format error
```
What am I doing wrong? :-)

**Comment by oriansj** [comment]
you also need to clone M2-Planet and mescc-tools as they provide the C source code used to in the full bootstrap

**Comment by practicalswift** [comment]
Thanks!

Now working as expected:

```
$ git clone -q https://github.com/oriansj/M2-Planet
$ git clone -q https://git.savannah.nongnu.org/git/mescc-tools.git
$ git clone -q https://github.com/oriansj/mescc-tools-seed
$ cd mescc-tools-seed && bash kaem.run && cd ..
$ sha256sum mescc-tools-seed/bin/*
fbccdcdd2a2b27c20856eab806320ded6992c8584857995228b0986404f21b37  mescc-tools-seed/bin/blood-elf
a8e333d219759e51e4b91a3a6662d3975d90a126afba284fbc2494834f71cd29  mescc-tools-seed/bin/get_machine
53cfac6ef615043659547e5f7e3b4173274c53aca351bafc88326b3cd9e86046  mescc-tools-seed/bin/hex2
04dd8ea2ea9eefdd7bfb2f375bd6d352cb2a2229d7efdc47c37f16f835dd5c81  mescc-tools-seed/bin/kaem
5cff752583c96b31fe5d712c8deb5cd7634482b4a7e78544b150733cb20c508a  mescc-tools-seed/bin/M1
67e558164795211e0ccd4e0564d0f0d41b76800df97a635c07bdf63d0cf9feda  mescc-tools-seed/bin/M2-Planet
b620c490de191c0885b32285c053d3745558617c3aaff67cbba27ac7382a464a  mescc-tools-seed/bin/placeholder
```

**Comment by practicalswift** [comment]
Very cool!

Just to make sure I understand the current state of bootstrapping correctly:

Now that I have `M2-Planet` the next step in bootstrapping process would be to build `Mes` using `M2-Planet`, right?

That work is not finished yet but takes place in the https://github.com/oriansj/mes-m2.

With `Mes` I can then build the simple C-compiler `MesCC`.

`Mes` and `MesCC` can then be used to build `tcc` (TinyCC) which in turn can be used to build `glibc`, `binutils` and `gcc`.

Am I describing it correctly?

Is it correct that all steps above are working as of today with the exception of `M2-Planet` to `mes` step (https://github.com/oriansj/mes-m2)?

**Comment by oriansj** [comment]
That is approximately correct.
